language: java
sudo: false
# Install services
services:
  - docker

before_script:
- docker pull openjdk:8-jre-alpine
script: 
- |
  echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin
  if [[ "$TRAVIS_PULL_REQUEST" == "false" ]] && [[ "$TRAVIS_BRANCH" == "master" ]]; then
    echo "On Branch $TRAVIS_BRANCH, building Latest images"
    ./gradlew dockerImage
    docker tag docker.io/frredacs/medicos-backend:${TRAVIS_BUILD_NUMBER} docker.io/frredacs/medicos-backend:latest
    docker push docker.io/frredacs/medicos-backend:${TRAVIS_BUILD_NUMBER} 
    docker push docker.io/frredacs/medicos-backend:latest
  else
    echo "On Branch $TRAVIS_BRANCH, checking build"
    ./gradlew check
  fi
