version: "3.7"
services:
  medicos-db:
    image: postgres
    ports:
     - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=medicos
    volumes:
      - postgres_medicos:/var/lib/postgresql/data
  medicos-backend:
    image: frredacs/medicos:0.0.1
    restart: always
    ports:
     - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql://medicos-db:5432/medicos
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
volumes:
  postgres_medicos:
