version: "3.7"
services:
  medicos-db:
    image: postgres
    ports:
     - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=medicos
    volumes:
      - postgres_medicos:/var/lib/postgresql/data
  medicos-backend:
    image: frredacs/medicos-backend:latest
    restart: always
    ports:
     - "8081:8081"
    environment:
      - DB_URL=jdbc:postgresql://medicos-db:5432/medicos
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
  medicos-frontend:
    image: frredacs/medicos-frontend:latest
    restart: always
    ports:
     - "80:80"
volumes:
  postgres_medicos:
