INSERT INTO especialidad (id, version, nombre, descripcion) VALUES
( 1, 0, 'ALERGIA E INMUNOLOGÍA', 'Es la especialidad médica que comprende el conocimiento, diagnóstico y tratamiento de la patología producida por mecanismos inmunológicos.'),
( 2, 0, 'ANATOMÍA PATOLÓGICA', ' es la especialidad que se ocupa del estudio, por medio de técnicas morfológicas, de las causas, el desarrollo y las consecuencias de las enfermedades. El fin último de esta especialidad es el diagnóstico correcto de biopsias, piezas quirúrgicas, citologías y autopsias.'),
( 3, 0, 'ANESTESIOLOGÍA', ' La anestesiología es la especialidad médica dedicada a la atención y cuidados especiales de los pacientes durante las intervenciones quirúrgicas u otros procesos que puedan resultar molestos o dolorosos endoscopia, radiología intervencionista, etc.). Así mismo, tiene a su cargo el tratamiento del dolor agudo o crónico de causa extraquirúrgica. Ejemplos de estos últimos son la analgesia durante el trabajo de parto y el alivio del dolor en pacientes con cáncer.'),
( 4, 0, 'ANGIOLOGÍA GENERAL y HEMODINAMIA', ' Es la especialidad médica que se encarga del estudio de los vasos del sistema circulatorio (venas y arterias) y del sistema linfático; incluyendo la anatomía de los vasos sanguíneos (como arterias, venas, capilares) y la de los linfáticos, además de sus enfermedades La hemodinámica es la que se encarga del estudio de la dinámica de la sangre en el interior de las estructuras sanguíneas como arterias, venas, vénulas, arteriolas y capilares así como también la mecánica del corazón'),
( 5, 0, 'CARDIOLOGÍA', ' Es la especialidad médica, encargada del estudio, diagnóstico y tratamiento de las enfermedades del corazón y del aparato circulatorio.'),
( 6, 0, 'CARDIÓLOGO INFANTIL', ' es la especialidad que tiene como fundamento la aplicación del saber y quehacer médico-quirúrgico cardiológico en el periodo de la vida humana que se extiende desde la concepción hasta la adolescencia.'),
( 7, 0, 'CIRUGÍA GENERAL', ' Es la especialidad médica que abarca las operaciones del aparato digestivo; incluyendo el tracto gastrointestinal y el sistema hepato-biliopancreático, el sistema endocrino; incluyendo las glándulas suprarrenales, tiroides, paratiroides, mama y otras glándulas incluidas en el aparato digestivo. Asimismo incluye la reparación de hernias y eventraciones de la pared abdominal.'),
( 8, 0, 'CIRUGÍA CARDIOVASCULAR', ' Es la especialidad quirúrgica que se ocupa del corazón o grandes vasos se utiliza para tratar complicaciones de la cardiopatía isquémica corregir malformaciones cardíacas congénitas, o tratar enfermedades valvulares del corazón debidas a causas diversas, como la endocarditis. También incluye el trasplante cardíaco.'),
( 9, 0, 'CIRUGÍA DE CABEZA Y CUELLO', ' Es la especialidad médica que se dedica al estudio, prevención, diagnóstico, tratamiento y rehabilitación de las enfermedades congénitas y adquiridas del cráneo, cara, cabeza y cuello, cavidad oral y maxilares (incluyendo la dentición). La patología adquirida puede ser de origen tumoral, traumático, por degeneración o envejecimiento.'),
(10, 0, 'CIRUGÍA DE TÓRAX (CIRUGÍA TORÁCICA)', ' La cirugía torácica es una especialidad médica dedicada al estudio y tratamiento quirúrgico de las enfermedades que afectan al tórax.'),
(11, 0, 'CIRUGÍA INFANTIL (CIRUGÍA PEDIÁTRICA)', ' La cirugía es la especialidad dedicada al diagnóstico, cuidado preoperatorio, operación y manejo postoperatorio de los problemas que presentan el feto, lactante, escolar, adolescente y joven adulto.'),
(12, 0, 'CIRUGÍA PLÁSTICA Y REPARADORA', ' Es la especialidad que tiene por objeto la corrección y/o mejoramiento de anormalidades de origen congénito, adquirido, tumoral o involutiva que requieran reparación o reposición de la forma corporal y su función.'),
(13, 0, 'CIRUGÍA VASCULAR PERIFÉRICA', ' La Angiología y Cirugía vascular es una especialidad médico-quirúrgica dedicada al estudio, prevención, diagnóstico clínico e instrumental y tratamiento de la patología vascular'),
(14, 0, 'CLÍNICA MÉDICA', ' Es una especialidad médica que atiende integralmente los problemas de salud en pacientes adultos, ingresados en un centro hospitalario o en consultas ambulatorias.'),
(15, 0, 'COLOPROCTOLOGÍA', ' Es la especialidad de la medicina derivada de la cirugía general que brinda diagnóstico y tratamiento quirúrgico y no quirúrgico de las enfermedades del cólon, recto y ano'),
(16, 0, 'DERMATOLOGÍA', ' Es la especialidad médica encargada del estudio de la estructura y función de la piel, así como de las enfermedades que la afectan, su diagnóstico, prevención y tratamiento.'),
(17, 0, 'DIAGNOSTICO POR IMÁGENES', ' Es la especialidad médica, que se ocupa de generar imágenes del interior del cuerpo mediante diferentes agentes físicos (rayos X, ultrasonidos, campos magnéticos, entre otros) y de utilizar estas imágenes para el diagnóstico de las enfermedades.'),
(18, 0, 'ENDOCRINOLOGÍA', ' es la especialidad médica que estudia el sistema endocrino y las enfermedades provocadas por un funcionamiento inadecuado del mismo.'),
(19, 0, 'ENDOCRINÓLOGO INFANTIL', ' Especialidad de la medicina que estudia la anatomía, funcionamiento y enfermedades del sistema endocrino y sus glándulas endocrinas, páncreas, tiroides, suprarrenales, hipófisis, gónadas del paciente pediátrico'),
(20, 0, 'FARMACOLOGÍA CLÍNICA', ' Es la especialidad que estudia la historia, el origen, las propiedades físicas y químicas, la presentación, los efectos bioquímicos y fisiológicos, los mecanismos de acción, la absorción, la distribución, la biotransformación y la excreción así como el uso terapéutico de los fármacos que interactúan con los organismos vivos.'),
(21, 0, 'FISIATRÍA (MEDICINA FÍSICA Y REHABILITACIÓN)', ' Es una especialidad de la medicina que promociona la salud y previene, diagnostica, evalúa, prescribe y trata el estado de enfermedad. Establece una prioridad en el logro de objetivos de funcionalidad ergonómicos, ocupacionales y de reintegración social.'),
(22, 0, 'GASTROENTEROLOGÍA', ' Es la especialidad médica que se ocupa de la atención, diagnóstico y tratamiento de las enfermedades del aparato digestivo y órganos asociados, conformado Por esófago, estómago, hígado y vías biliares, páncreas, intestino delgado (duodeno, yeyuno, íleon), colon y recto.'),
(23, 0, 'GASTROENTERÓLOGO INFANTIL', ' Es la Especialidad que atiende niños y adolescentes con enfermedades digestivas (esófago, estómago e intestino) y enfermedades hepáticas.'),
(24, 0, 'GENÉTICA MEDICA', ' Es la aplicación de la genética en el contexto de la medicina. El campo de aplicación de la genética médica es amplio y variado. Incluye diferentes áreas individuales tales como la genética clínica, la genética bioquímica, la genética molecular, la citogenética, la genética de enfermedades comunes y el consejo o asesoramiento genético.'),
(25, 0, 'GERIATRÍA', ' Es una especialidad médica dedicada al estudio de la prevención, el diagnóstico, el tratamiento y la rehabilitación de las enfermedades en las personas de la tercera edad.'),
(26, 0, 'GINECOLOGÍA', ' La ginecología es una especialidad médica, pero también tiene algunas vertientes quirúrgicas. se dedica al estudio y tratamiento de diversos problemas y enfermedades del aparato genital femenino.'),
(27, 0, 'HEMATOLOGÍA', ' Es la especialidad médica que se dedica al tratamiento de los pacientes con enfermedades de la sangre o hematológicas.'),
(28, 0, 'HEMATÓLOGO INFANTIL', ' La hematología estudia y trata las enfermedades de la sangre relacionadas con alteraciones de los glóbulos rojos (como los distintos tipos de anemias), glóbulos blancos (neutropenias congénitas, adquiridas o malignas), y plaquetas (como las púrpuras). También las enfermedades hemorrágicas, principalmente hemofilias'),
(29, 0, 'HEMOTERAPIA E INMUNOHEMATOLOGÍA', 'Ley de sangre 22.990/83 por decreto 1338/04 en su Art 5. Se entiende por Hemoterapia la especialidad médica que comprende la dirección, implementación y evaluación de los procesos antes citados, los que se deberán realizar en estrecha vinculación interdisciplinaria con las demás profesiones (en especial en lo referente a la producción de hemoderivados y la detección y control de infecciones transmisibles por transfusión) y con las especialidades médicas que intervienen en la atención de los pacientes, en particular en cuanto al diagnóstico, tratamiento y prevención de las enfermedades citopénicas perinatales, en las enfermedades inmunohematológicas, en los procedimientos de aféresis terapéutica y de autotransfusión en todas sus modalidades".'),
(30, 0, 'INFECTOLOGÍA', ' La infectología es especialidad de la medicina interna y de la pediatría que se encarga del estudio, la prevención, el diagnóstico, tratamiento y pronóstico de las enfermedades producidas por agentes infecciosos (bacterias, virus, hongos y parásitos).'),
(31, 0, 'INFECTÓLOGO INFANTIL', ' Es la especialidad médica en el área de la pediatría que se encarga de la prevención, diagnóstico y tratamiento de Enfermedades Infecciosas, enfermedades causadas por virus, bacterias, hongos y parásitos.'),
(32, 0, 'MEDICINA DEL DEPORTE', ' Es la especialidad médica que estudia los efectos del ejercicio del deporte y, en general, de la actividad física, en el organismo humano, desde el punto de vista de la prevención y tratamiento de las enfermedades y lesiones.'),
(33, 0, 'MEDICINA GENERAL y/o MEDICINA DE FAMILIA', ' Es especialidad médica que proporciona atención sanitaria continua e integral al individuo y a la familia. Es la especialidad que integra las ciencias biológicas, clínicas, sociales y del comportamiento. El ámbito de la medicina familiar abarca todas las edades, ambos sexos, cada uno de los sistemas orgánicos y todas las enfermedades. Orientada a la Atención Primaria.'),
(34, 0, 'MEDICINA LEGAL', ' Es la especialidad que permite al profesional médico especializado, realizar informes técnicos y pericias relacionadas a sus especialidades asistenciales, asistir a Magistrados cuando éste lo requiera, pudiendo establecer, causalidades sobre los daños físicos reclamados y fijar eventuales incapacidades físicas conforme a derecho.'),
(35, 0, 'MEDICINA NUCLEAR', ' Es una especialidad que diagnostica y determina la gravedad y tratamiento de una o varias enfermedades, incluyendo cáncer en diversos tipos, enfermedades cardíacas, gastrointestinales, endocrinas, desórdenes neurológicos, y otras anomalías dentro del cuerpo donde se utilizan radiotrazadores o radiofármacos, que están formados por un fármaco transportador y un isótopo radiactivo. Estos radiofármacos se aplican dentro del organismo humano por diversas vías (la más utilizada es la vía intravenosa). Una vez que el radiofármaco está dentro del organismo, se distribuye por diversos órganos dependiendo del tipo de radiofármaco empleado. La distribución del radiofármaco es detectado por un aparato detector de radiación llamado gammacámara y almacenado digitalmente. Luego se procesa la información obteniendo imágenes de todo el cuerpo o del órgano en estudio. Estas imágenes, a diferencia de la mayoría de las obtenidas en radiología, son imágenes funcionales y moleculares, es decir, muestran como están funcionando'),
(36, 0, 'MEDICINA DEL TRABAJO', ' Es la especialidad médica que se dedica al estudio de las enfermedades y los accidentes que se producen por causa o consecuencia de la actividad laboral, así como las medidas de prevención que deben ser adoptadas para evitarlas o aminorar sus consecuencias'),
(37, 0, 'NEFROLOGÍA', ' Es la especialidad clínica que se ocupa del estudio de la anatomía, fisiología, patología, promoción de salud, prevención, clínica, terapéutica y rehabilitación de las enfermedades del aparato urinario en su totalidad.'),
(38, 0, 'NEFRÓLOGO INFANTIL', ' La nefrología infantil se dedica a diagnosticar y tratar las enfermedades de todo el tracto urinario en los niños'),
(39, 0, 'NEONATOLOGÍA', ' es una especialidad dedicada a la atención del recién nacido hasta los 28 días, sea éste sano o enfermo, termino, pretermino dividida en recién nacido inmediato hasta 48 horas de vida y mediato hasta 28 días de vida'),
(40, 0, 'NEUMONOLOGÍA', ' Es la especialidad médica encargada del estudio de las enfermedades del aparato respiratorio y centra su campo de actuación en el diagnóstico, tratamiento y prevención de las enfermedades del pulmón la pleura y el mediastino.'),
(41, 0, 'NEUMONÓLOGO INFANTIL', ' Es la especialidad médica encargada del estudio de las enfermedades del aparato respiratorio y centra su campo de actuación en el diagnóstico, tratamiento y prevención de las enfermedades del pulmón la pleura y el mediastino desde el recién nacido al adolescente.'),
(42, 0, 'NEUROCIRUGÍA', ' Es la especialidad médica que se encarga del manejo quirúrgico (incluyendo la educación, prevención, diagnóstico, evaluación, tratamiento, cuidados intensivos, y rehabilitación) de determinadas enfermedades del sistema nervioso central, periférico y vegetativo, incluyendo sus estructuras vasculares'),
(43, 0, 'NEUROLOGÍA', ' Es la especialidad médica que trata los trastornos del sistema nervioso, su prevención, diagnóstico, tratamiento y rehabilitación.'),
(44, 0, 'NEURÓLOGO INFANTIL', ' Es la especialidad médica que trata los trastornos del sistema nervioso en pediatria.'),
(45, 0, 'NUTRICIÓN', ' Es la especialidad médica que estudia la alimentación humana y su relación con los procesos químicos, biológicos y metabólicos, así como su relación con la composición corporal y estado de salud humana. La nutrición comprende el estudio de los alimentos, los nutrientes, su clasificación, digestión así como su asimilación, metabolismo y excreción. Establece la necesidad de los nutrientes y su requerimiento en situaciones especiales, así como su relación con la salud y la enfermedad. Dietas para diabéticos, hipertensos'),
(46, 0, 'OBSTETRICIA', ' La especialidad médica que se ocupa del embarazo, el parto y el puerperio.'),
(47, 0, 'OFTALMOLOGÍA', ' Es la especialidad médica que estudia las enfermedades de ojo y su tratamiento, incluyendo el globo ocular, su musculatura, el sistema lagrimal y los párpados'),
(48, 0, 'ONCOLOGÍA', ' Especialidad médica dedicada al diagnóstico y tratamiento del cáncer.'),
(49, 0, 'ONCÓLOGO INFANTIL', ' Especialidad de la pediatría que se preocupa de diagnóstico, tratamiento y seguimiento del cáncer infantil.'),
(50, 0, 'ORTOPEDIA Y TRAUMATOLOGÍA', ' Es la especialidad médica que se dedica al estudio de las lesiones del aparato locomotor. La especialidad es médico quirúrgica, su ámbito se extiende más allá del campo de las lesiones traumáticas; abarca el estudio de las enfermedades congénitas o adquiridas que afectan al aparato locomotor, especialmente de aquellas que precisan tratamiento con cirugía, prótesis. Algunos de las enfermedades de las que se ocupa la traumatología son las fracturas y luxaciones de los huesos, las lesiones de ligamentos, tendones y músculos, también los tumores óseos y afecciones de la columna vertebral como la hernia discal y la escoliosis.'),
(51, 0, 'OTORRINOLARINGOLOGÍA', ' Es la especialidad médica que se encarga del estudio tanto médico como quirúrgico, de las enfermedades del oído, las vías aéreorespiratorias superiores y parte de las inferiores, incluyendo nariz, senos paranasales, faringe y laringe.'),
(52, 0, 'PEDIATRÍA', ' La pediatría es la especialidad que estudia al niño y sus enfermedades. Pero su contenido es mucho mayor que la curación de las enfermedades de los niños, ya que la pediatría estudia tanto al niño sano como al enfermo. Cronológicamente, la pediatría abarca desde el nacimiento hasta la adolescencia. Dentro de ella se distinguen varios periodos recién nacido (0-6 días), neonato (7-29 días), lactante (lactante menor 1-12 meses de vida, lactante mayor 1-2 años), preescolar (2-5 años), escolar (5-10 años), pre-adolescente (10-12 años) y adolescente (12-18 años).'),
(53, 0, 'PSIQUIATRÍA', ' Es la especialidad de la medicina que se ocupa del estudio, el diagnóstico, el tratamiento y la prevención de las enfermedades mentales de carácter orgánico y no orgánico.'),
(54, 0, 'PSIQUIATRÍA INFANTO JUVENIL', ' Es la especialidad de la medicina que se ocupa del estudio, el diagnóstico, el tratamiento y la prevención de las enfermedades mentales de carácter orgánico y no orgánico, de las distintas etapas del desarrollo de la población infanto-juvenil.'),
(55, 0, 'RADIOTERAPIA O TERAPIA RADIANTE', ' Es una especialidad médica , dedicada a los aspectos diagnósticos, cuidados clínicos y terapéuticos del enfermo oncológico, primordialmente orientada al empleo de los tratamientos con radiaciones. Emplea rayos X y rayos gamma de alta energía (fotones de alta energía), haces de electrones y otras radiaciones ionizantes para el tratamiento de ciertas clases de cáncer.'),
(56, 0, 'REUMATOLOGÍA', ' Es una especialidad médica, rama de la medicina interna y la pediatría, dedicada a los trastornos médicos del aparato locomotor y del tejido conectivo, que abarca un gran número de entidades clínicas conocidas en conjunto como enfermedades reumáticas, a las que se suman un gran grupo de enfermedades de afectación sistémica las enfermedades del colágeno'),
(57, 0, 'REUMATÓLOGO INFANTIL', ' Es la especialidad pediátrica en la evaluación y tratamiento de diversos trastornos de las articulaciones, los músculos y los huesos'),
(58, 0, 'TERAPIA INTENSIVA', ' Es una especialidad médica dedicada al suministro de soporte vital o de soporte a los sistemas orgánicos.'),
(59, 0, 'TERAPISTA INTENSIVO INFANTIL', ' Es una especialidad médica dedicada al suministro de soporte vital o de soporte a los sistemas orgánicos en los pacientes pediátricos que están críticamente enfermos, quienes generalmente también requieren supervisión y monitorización intensiva.'),
(60, 0, 'TOCOGINECOLOGÍA', ' Es especialidad médica y quirúrgica que trata las enfermedades del sistema reproductor femenino (útero, vagina y ovarios). Además existe, relación, la especialidad de obstetricia, a tal punto que casi todos los ginecólogos modernos son también médicos obstetras la especialidad médica que se ocupa del embarazo, el parto y el puerperio, principalmente en situaciones de riesgo que requieran de una intervención quirúrgica. Como especialidad médica la obstetricia es combinada con la ginecología bajo la disciplina conocida como obstetricia y ginecología (toco ginecólogo).'),
(61, 0, 'TOXICOLOGÍA', ' Una especialidad médica que estudia los efectos nocivos de los agentes químicos y de los agentes físicos (agentes tóxicos) en los sistemas biológicos y que establece además, la magnitud del daño en función de la exposición de los organismos vivos a dichos agentes. Se ocupa de la naturaleza y de los mecanismos de las lesiones y de la evaluación de los diversos cambios biológicos producidos por los agentes'),
(62, 0, 'UROLOGÍA', ' Es la especialidad médico-quirúrgica que se ocupa del estudio, diagnóstico y tratamiento de las patologías que afectan al aparato urinario, glándulas suprarrenales y retroperitoneo de hombres y mujeres y el aparato reproductor masculino.');

-- Obras Sociales

INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(1, 0,126700, 'OBRA SOCIAL DEL PERSONAL DE LA ACTIVIDAD AZUCARERA TUCUMANA', '', 'CONGRESO DE TUCUMAN 341', 4000, 'TUCUMAN', '', '', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(2, 0,103006, 'OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA BOTONERA', 'OSPIB', 'CALLE 91 N# 1886', 1650, 'BUENOS AIRES', '', '', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(3, 0,121606, 'OBRA SOCIAL CONDUCTORES DE TRANSPORTE COLECTIVO DE PASAJEROS', '', 'MORENO 2969', 1209, 'CAPITAL FEDERAL', 'INT 109.183,155,117,', '', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(4, 0,121705, 'OBRA SOCIAL DEL PERSONAL DE LA ACTIVIDAD DEL TURF', 'OSPAT', 'FLORIDA 15 PISO 4 DERECHA', 1005, 'CAPITAL FEDERAL', '0800-999-1656', '', 'www.ospat.com.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(5, 0,109202, 'OBRA SOCIAL DE GUINCHEROS Y MAQUINISTAS DE GRUAS MOVILES', '', 'CORONEL SALVADORES 1638', 1296, 'CAPITAL FEDERAL', '', 'osguincheros@compulogic.com.ar', 'www.osocialguincheros.com', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(6, 0,107008, 'OBRA SOCIAL DEL PERSONAL DE ESCRIBANOS', 'OSPE', 'RODRIGUEZ PE—A 536/38', 1020, 'CAPITAL FEDERAL', '', 'obrasocial@ospe.org.ar', 'www.ospe.org.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(7, 0,108704, 'OBRA SOCIAL DE TECNICOS DE FUTBOL', 'OSTECF', 'VIAMONTE 1328 PB PISO 1', 1053, 'CAPITAL FEDERAL', '', '', 'www.ostecf.com.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(8, 0,111209, 'OBRA SOCIAL DEL PERSONAL DE MAESTRANZA', 'OSPM', 'ALZAGA 2271', 1240, 'CAPITAL FEDERAL', '0800-333-8154', 's-o-m@satlink.com', 'www.somlimpieza.com.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(9, 0,112608, 'OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA MOLINERA', 'OSPIM', 'AV. SAN JUAN 2670/72', 1232, 'CAPITAL FEDERAL', '', 'info@ospim.org.ar', 'www.ospim.org.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(10, 0,116204, 'OBRA SOCIAL DE PORTUARIOS ARGENTINOS', 'OSPA', 'BOLIVAR 839', 1066, 'CAPITAL FEDERAL', '', 'ospabue@infovia.com.ar', 'www.ospaport.com.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(11, 0,117801, 'OBRA SOCIAL DEL PERSONAL DE PRENSA DE MENDOZA', '', 'CHILE 1661', 5500, 'MENDOZA', '', 'prensaludmza@hprensaludmza.org.ar', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(12, 0,100700, 'OBRA SOCIAL DEL PERSONAL TECNICO AERONAUTICO', 'OSPTA', 'D ONOFRIO 158', 1702, 'BUENOS AIRES', '0800--666-2096', 'aviones@aviones.com', 'www.aviones.com', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(13, 0,105606, 'OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA DEL CUERO Y AFINES', 'OSPICA', 'CALLE GIRIBONE 789', 1872, 'BUENOS AIRES', '', '', 'www.ospica.org.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(14, 0,106500, 'OBRA SOCIAL DEL PERSONAL DE EDIFICIOS DE RENTA Y HORIZONTAL DE LA CIUDAD AUTONOMA DE BUENOS AIRES Y GRAN BUENOS AIRES', 'OSPERYH', 'SARMIENTO 2026', 1044, 'CAPITAL FEDERAL', '0800-266-0066', 'osperyh@osperyh.org.ar', 'www.fateryh.org.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(15, 0,118200, 'OBRA SOCIAL DE AGENTES DE PROPAGANDA MEDICA DE LA REPUBLICA ARGENTINA', 'OSAPM', 'AVELLANEDA 2144', 1406, 'CAPITAL FEDERAL', '', 'obra_social@apm.org.ar', 'www.apm.org.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(16, 0,124506, 'OBRA SOCIAL DE TRABAJADORES DE LA INDUSTRIA DEL GAS', 'OSTIG', 'BOEDO 90', 1206, 'CAPITAL FEDERAL', '', 'ostig@impsat 1.com.ar.', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(17, 0,106203, 'OBRA SOCIAL DEL PERSONAL DE DISTRIBUIDORAS CINEMATOGRAFICAS DE LA R.A.', 'OSPEDICI', 'AYACUCHO 512/514 1∫ Y 2∫ PISO', 1025, 'CAPITAL FEDERAL', '', 'info@ospedici.org.ar', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(18, 0,128607, 'OBRA SOCIAL DE TRABAJADORES DEL PETROLEO Y GAS PRIVADO DEL CHUBUT', '', 'AVDA ALSINA 728 PISO 3', 9000, 'CHUBUT', '', '', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(19, 0,112103, 'OBRA SOCIAL DE LA UNION OBRERA METALURGICA DE LA REPUBLICA ARGENTINA', 'OSUOMRA', 'ALSINA 485 - PISO 4', 1087, 'CAPITAL FEDERAL', '', '', 'www.forjarsalud.com.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(20, 0,103204, 'OBRA SOCIAL DE CONDUCTORES CAMIONEROS Y PERSONAL DEL TRANSPORTE AUTOMOTOR DE CARGAS', '', 'AV. CASEROS 921/23', 1152, 'CAPITAL FEDERAL', '', 'aliciak@spdps.com.ar', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(21, 0,108605, 'OBRA SOCIAL DE FUTBOLISTAS', 'FAA', 'SALTA 1144', 1074, 'CAPITAL FEDERAL', '', 'agremiados@infovia.com.ar', 'www.agremiados.com.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(22, 0,127901, 'OBRA SOCIAL DE PETROLEROS PRIVADOS', 'OS.PE.PRI', 'SANTA CRUZ 275', 8300, 'NEUQUEN', '0800-333-8448', 'mildepetroleo@speedy.com.ar', 'www.ospepri.org.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(23, 0,111001, 'OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA MADERERA', 'OSPIM', 'ROJAS 254', 1405, 'CAPITAL FEDERAL', '', 'contacto@ospim.com.ar', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(24, 0,118705, 'OBRA SOCIAL DEL PERSONAL DE INDUSTRIAS QUIMICAS Y PETROQUIMICAS', 'OSPIQYP', 'MEXICO 1474', 1097, 'CAPITAL FEDERAL', '', '', 'www.ospiqyp.org.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(25, 0,104009, 'OBRA SOCIAL DEL PERSONAL DE CEMENTERIOS DE LA REPUBLICA ARGENTINA.', 'OSPCRA', 'FEDERICO LACROZE 3908', 1427, 'CAPITAL FEDERAL', '0800-555-6772', 'soecra@uolsinectis.com.ar', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(26, 0,123404, 'OBRA SOCIAL DEL PERSONAL DE PRENSA DE ROSARIO', 'OSPRO', 'JUAN MANUEL DE ROSAS 958', 2000, 'SANTA FE', '', 'ospro@arnet.com.ar', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(27, 0,110800, 'OBRA SOCIAL DE LOS TRABAJADORES DE LAS EMPRESAS DE ELECTRICIDAD', 'OSTEE', 'HUMBERTO 1∫ 434', 1103, 'CAPITAL FEDERAL', '0800-999-1534', 'obrasocial@osteeluzmedica.com.ar', 'www.osteeluzmedica.com.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(28, 0,118408, 'OBRA SOCIAL DE AGENTES DE PROPAGANDA MEDICA DE ENTRE RIOS', 'OSAPMER', 'CATAMARCA 451', 3100, 'ENTRE RIOS', '', 'apmentrario@infovia.com.ar', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(29, 0,123008, 'OBRA SOCIAL PARA EL PERSONAL DE ESTACIONES DE SERVICIO, GARAGES, PLAYAS DE ESTACIONAMIENTO, LAVADEROS AUTOMATICOS Y GOMERIAS DE LA REPUBLICA ARGENTINA', 'OSPES', 'AVDA. JUJUY 110 PISO 3 DTOS A , B', 1083, 'CAPITAL FEDERAL', '', 'central@ospes.org.ar', 'www.ospes.org.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(30, 0,104405, 'OBRA SOCIAL DEL PERSONAL CINEMATOGRAFICO DE MAR DEL PLATA', 'OSPERCIN', 'NEUQUEN 2655', 7600, 'BUENOS AIRES', '', '', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(31, 0,105507, 'OBRA SOCIAL DE LOS CORTADORES DE LA INDUMENTARIA', 'OSUCI', 'SANTIAGO DEL ESTERO 576', 1075, 'CAPITAL FEDERAL', '', 'obrasocial@uci.org.ar', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(32, 0,104801, 'OBRA SOCIAL DE COLOCADORES DE AZULEJOS, MOSAICOS, GRANITEROS, LUSTRADORES Y PORCELANEROS', 'OSCAMGLYP', 'JOSE EUSEBIO COLOMBRES 1419', 1238, 'CAPITAL FEDERAL', '', 'oscamglyp@speedy.com.ar', 'no poseen', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(33, 0,104603, 'OBRA SOCIAL DE OPERADORES CINEMATOGRAFICOS', 'OSOC', 'VIAMONTE 2045', 1056, 'CAPITAL FEDERAL', '', '', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(34, 0,116709, 'OBRA SOCIAL PORTUARIOS PUERTO SAN MARTIN Y BELLA VISTA', '', 'CAYETANO NERBUTTI 256', 2202, 'SANTA FE', '', 'obrasocial@cooportuaria.com', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(35, 0,104306, 'OBRA SOCIAL DEL PERSONAL DE LA ACTIVIDAD CERVECERA Y AFINES', 'OSPACA', 'HUMAHUACA 4072', 1192, 'CAPITAL FEDERAL', '0800-3336772', 'consultas@oscervecera.org.ar', 'www.oscervecera.org.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(36, 0,106708, 'OBRA SOCIAL DE OBREROS EMPACADORES DE FRUTA DE RIO NEGRO Y NEUQUEN', '', 'MENGUELLE 130', 8324, 'RIO NEGRO', '', 'victoria@neunt.com.ar', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(37, 0,104207, 'OBRA SOCIAL DEL PERSONAL DE LA CERAMICA, SANITARIOS, PORCELANA DE MESA Y AFINES', 'OSPCSPMYA', 'AV. HIIPOLITO IRIGOYEN 1255', 1870, 'BUENOS AIRES', '', 'ospecesa@speedy.com.ar', 'www.ospecesa.com.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(38, 0,108803, 'OBRA SOCIAL DE LA UNION DE TRABAJADORES DEL TURISMO, HOTELEROS Y GASTRONOMICOS DE LA REPUBLICA ARGENTINA', 'OSUTHGRA', 'AVDA. DE MAYO 930', 1084, 'CAPITAL FEDERAL', '0800-222-8844', 'info@uthgra.org.ar', 'www.uthgra.org.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(39, 0,109509, 'OBRA SOCIAL DEL PERSONAL DE LOS HIPODROMOS DE BUENOS AIRES Y SAN ISIDRO', 'OSPHGBAYSI', 'JURAMENTO 1590 PISO 1', 1428, 'CAPITAL FEDERAL', '', 'osphbaysi@fibertel.com.ar.', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(40, 0,113304, 'OBRA SOCIAL DE JEFES Y OFICIALES MAQUINISTAS NAVALES', 'OSJOMN', 'RODRIGUEZ PE—A 1464', 1021, 'CAPITAL FEDERAL', '', 'infoobrasocial@osjomn.com.ar', 'www.maquinaval.com.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(41, 0,118309, 'OBRA SOCIAL DE AGENTES DE PROPAGANDA MEDICA DE CORDOBA', '', 'AVDA OLMOS 485 PISO 2 (ESQUINA STAGO DEL ESTERO)', 5003, 'CORDOBA', '', 'osapm@arnet.com.ar', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(42, 0,127000, 'OBRA SOCIAL DE TRABAJADORES DE ESTACIONES DE SERVICIO', 'OSTES', 'BANDERA DE LOS ANDES 239', 5521, 'MENDOZA', '', '', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(43, 0,104504, 'OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA CINEMATOGRAFICA', 'OSPIC', 'JUNCAL 2029', 1116, 'CAPITAL FEDERAL', '', 'ospic@sicacine.org.ar', 'www.sicacine.com.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(44, 0,113205, 'OBRA SOCIAL DE JEFES Y OFICIALES NAVALES DE RADIOCOMUNICACIONES', 'OSJONR', '24 DE NOVIEMBRE 643/5', 1224, 'CAPITAL FEDERAL', '', 'radionaval@arnet.com.ar', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(45, 0,113403, 'OBRA SOCIAL DEL PERSONAL NAVAL', 'OSPENA', 'JUAN DE DIOS FILIBERTO 914', 1162, 'CAPITAL FEDERAL', '', 'ospena1340@hotmail.com', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(46, 0,112202, 'OBRA SOCIAL DE LOS SUPERVISORES DE LA INDUSTRIA METALMECANICA DE LA REPUBLICA ARGENTINA', 'OSSIMRA', 'AZCUENAGA 1234', 1115, 'CAPITAL FEDERAL', '0-800-888-2746', 'asinra@arnet.com.ar', 'www.ossimra.org.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(47, 0,126601, 'OBRA SOCIAL DEL PERSONAL DE INDUSTRIAS QUIMICAS Y PETROQUIMICAS DE ZARATE CAMPANA', 'OPZC', 'DR FELIX PAGOLA 1712', 2800, 'BUENOS AIRES', '', 'info@obrasocialquimicos.com.ar', 'www.obrasocialquimicos.com.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(48, 0,114703, 'OBRA SOCIAL DEL PERSONAL DE PELUQUERIAS, ESTETICAS Y AFINES', 'OSPPEA', 'AYACUCHO 838', 1111, 'CAPITAL FEDERAL', '', 'obrasocial@peluquerosargentinos.com', 'www.peluquerosargentinos.com', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(49, 0,103105, 'OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA DEL CALZADO', 'OSPICAL', 'YATAY 129 PISO 4', 1184, 'CAPITAL FEDERAL', '', 'institucional@ospical.org.ar', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(50, 0,114208, 'OBRA SOCIAL DE LA INDUSTRIA DE PASTAS ALIMENTICIAS', 'OSIPA', 'AVDA.. BELGRANO 4280', 1210, 'CAPITAL FEDERAL', '', 'stipa@arnet.com.ar', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(51, 0,112806, 'OBRA SOCIAL DE MUSICOS', 'OSDEM', 'AVDA. BELGRANO 3655', 1210, 'CAPITAL FEDERAL', '', 'sadem@interlink.com.ar', 'www.sadem.com.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(52, 0,113601, 'OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA DEL NEUMATICO', 'OSPIN', 'JUJUY 995', 1229, 'CAPITAL FEDERAL', '', 'ospin@sinectis.com.ar', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(53, 0,101901, 'OBRA SOCIAL DEL PERSONAL DEL AZUCAR DEL INGENIO LEDESMA', 'OSPAIL', 'JUJUY 755 CC5', 4512, 'JUJUY', '', '', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(54, 0,120405, 'OBRA SOCIAL DEL PERSONAL DE DIRECCION DE LA EMPRESA SUBTERRANEOS DE BUENOS AIRES', 'OSPDESBA', 'AVDA CALLAO 322 PISO 8 DTO A', 1022, 'CAPITAL FEDERAL', '', 'ospdesba@speedy.com.ar', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(55, 0,114000, 'OBRA SOCIAL DE PANADEROS, PASTELEROS Y FACTUREROS DE ENTRE RIOS', 'OSSPYFER', 'VELEZ SARSFIELD 447/49', 3200, 'ENTRE RIOS', '', '', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(56, 0,118804, 'OBRA SOCIAL DE RECIBIDORES DE GRANOS Y ANEXOS', 'OSRGA', 'AVDA BELGRANO 510 PISO 5', 1092, 'CAPITAL FEDERAL', '', '', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(57, 0,128706, 'OBRA SOCIAL DEL PERSONAL DE DRAGADO Y BALIZAMIENTO', 'OSPEDYB', 'CALLE PIEDRAS 1693/95', 1140, 'CAPITAL FEDERAL', '', 'ospedyb@gmail.com', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(58, 0,122302, 'OBRA SOCIAL DEL PERSONAL DE LA ACTIVIDAD VIAL', 'OSPA-VIAL', 'AVDA. DE MAYO 1439', 1085, 'CAPITAL FEDERAL', '', 'ospacentral@yahoo.com.ar', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(59, 0,120306, 'OBRA SOCIAL DEL PERSONAL DE SUPERVISION DE LA EMPRESA SUBTERRANEOS DE BUENOS AIRES', 'OSPSESBA', 'EMILIO MITRE 582', 1424, 'CAPITAL FEDERAL', '', 'ospesba@fibertel.com.ar', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(60, 0,101802, 'OBRA SOCIAL DEL PERSONAL DEL AZUCAR DEL INGENIO LA ESPERANZA', 'OSPA', 'SERAPIO SORIA 337', 4500, 'JUJUY', '', 'ospalesp@arnetbiz,com.ar', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(61, 0,120504, 'OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA DEL TABACO', 'OSPIT', 'ESTEBAN BONORINO 281', 1406, 'CAPITAL FEDERAL', '', 'ospitabaco@infovia.com.ar', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(62, 0,119005, 'OBRA SOCIAL DEL PERSONAL DE REFINERIAS DE MAIZ', '', 'ANCHORENA 1429', 2942, 'BUENOS AIRES', '', 'Osprem@arnetbiz.com.ar', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(63, 0,103402, 'OBRA SOCIAL DEL PERSONAL DE CARGA Y DESCARGA', 'OSPCYD', 'COCHABAMBA 1635', 1148, 'CAPITAL FEDERAL', '', 'estibaro@hotmail.com.ar', 'www.geocities.com', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(64, 0,122807, 'OBRA SOCIAL DEL PERSONAL DE VIGILANCIA Y SEGURIDAD COMERCIAL, INDUSTRIAL E INVESTIGACIONES PRIVADAS DE CORDOBA', 'OSPEVIC', 'FAUSTINO ALLENDE 189 - BARRIO INDEPENDENCIA', 5000, 'CORDOBA', '0810-888-6773', 'ospevic@ospevic.org.ar', 'www.ospevic.org.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(65, 0,123909, 'OBRA SOCIAL DE VENDEDORES AMBULANTES DE LA REPUBLICA ARGENTINA', 'OSVARA', 'GALLO 443', 1172, 'CAPITAL FEDERAL', '', '', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(66, 0,110404, 'OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA LADRILLERA A MAQUINA', 'OSPILM', '25 DE MAYO 1724 E/ LINCOLN Y JUAREZ (79 1724 E 46/', 1650, 'BUENOS AIRES', '', 'institucional@ospilm.org.ar', 'www.ospilm.org.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(67, 0,125103, 'OBRA SOCIAL DE LOS PROFESIONALES UNIVERSITARIOS DEL AGUA Y LA ENERGIA ELECTRICA', 'OSPUAYE', 'RECONQUISTA 1048 PISO 2', 1003, 'CAPITAL FEDERAL', '', 'ospuaye@apuaye.org.ar', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(68, 0,124001, 'OBRA SOCIAL DE BOXEADORES AGREMIADOS DE LA REPUBLICA ARGENTINA', 'OSBARA', 'TALCAHUANO 109 PISO 6 D', 1013, 'CAPITAL FEDERAL', '', '', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(69, 0,121507, 'OBRA SOCIAL DE LA INDUSTRIA DEL TRANSPORTE AUTOMOTOR DE CORDOBA', 'OSITAC', 'PARANA 327', 5000, 'CORDOBA', '', 'aoita@ositac.org.ar', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(70, 0,103600, 'OBRA SOCIAL DEL PERSONAL AUXILIAR DE CASAS PARTICULARES', 'OSPACP', 'CHARCAS 2745', 1425, 'CAPITAL FEDERAL', '0800-888-2748', 'info@ospacp.org.ar', 'www.ospacp.org.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(71, 0,113809, 'OBRA SOCIAL DE COMISARIOS NAVALES', '', 'BERNARDO DE IRIGOYEN 840', 1072, 'CAPITAL FEDERAL', '0800-333-6726', '', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(72, 0,128102, 'OBRA SOCIAL DE LA UNION DE TRABAJADORES DEL INSTITUTO NACIONAL DE SERVICIOS SOCIALES PARA JUBILADOS Y PENSIONADOS DE LA REPUBLICA ARGENTINA', 'OSUTI', 'ESMERALDA 25', 1035, 'CAPITAL FEDERAL', '0800-666-7884', '', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(73, 0,128003, 'OBRA SOCIAL DEL PERSONAL DE LA FEDERACION DE SINDICATOS DE LA INDUSTRIA QUIMICA Y PETROQUIMICA', '', 'PAVON 3708', 1253, 'CAPITAL FEDERAL', '', 'festiqypra tesoreria@live.com.ar', 'www.festiqypra.org.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(74, 0,100304, 'OBRA SOCIAL DE TECNICOS DE VUELO DE LINEAS AEREAS', 'OSTVLA', 'VICTOR HUGO 369', 1407, 'CAPITAL FEDERAL', '', 'obrasocial@tecnicosdevuelo.org.ar', 'www.tecnicosdevuelo.org.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(75, 0,126908, 'OBRA SOCIAL DE LOS MEDICOS DE LA CIUDAD DE BUENOS AIRES', 'OSMEDICA', 'MARCELO T. DE ALVEAR 867/871', 1058, 'CAPITAL FEDERAL', '0800-999-5396', 'obrasocial@osmedica.com.ar', 'www.osmedica.com.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(76, 0,103907, 'OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA DEL CAUCHO DE SANTA FE', 'OSPIC SANTA FE', 'ITURRASPE 2458', 3034, 'SANTA FE', '', 'oscauchostafe@yahoo.com.ar', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(77, 0,119302, 'OBRA SOCIAL DEL PERSONAL RURAL Y ESTIBADORES DE LA REPUBLICA ARGENTINA', 'OSPRERA', 'RECONQUISTA 630', 1003, 'CAPITAL FEDERAL', '0800-77-78725', '', 'www.osprera.com.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(78, 0,127406, 'OBRA SOCIAL DE OBREROS Y EMPLEADOS TINTOREROS SOMBREREROS Y LAVADEROS DE LA REPUBLICA ARGENTINA', 'OSOETSYLARA', 'CULPINA 25/29', 1406, 'CAPITAL FEDERAL', '', '', 'www.uoesylra.org', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(79, 0,128201, 'OBRA SOCIAL DEL SINDICATO UNICO DE RECOLECTORES DE RESIDUOS Y BARRIDO DE CORDOBA', 'O.S.S.U.R.R.B.A.C', 'LIMA 342', 5000, 'CORDOBA', '', 'surrbacinstitucional@gmail.com', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(80, 0,105002, 'OBRA SOCIAL DE CONDUCTORES NAVALES', 'OSCONARA', 'PINZON 281', 1161, 'CAPITAL FEDERAL', '', 'info@siconara.com.ar', 'www.siconara.org.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(81, 0,109707, 'OBRA SOCIAL DEL PERSONAL DE IMPRENTA, DIARIOS Y AFINES', 'OSPIDA', 'SAN JOSE 157', 1076, 'CAPITAL FEDERAL', '', 'ospida@ospida.org.ar', 'www.ospida.org.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(82, 0,121101, 'OBRA SOCIAL DE EMPLEADOS TEXTILES Y AFINES', 'OSETYA', 'BENITO QUINQUELA MARTIN 1738', 1433, 'CAPITAL FEDERAL', '0810-999-6738', 'informes@osetya.com.ar', 'www.osetya.com.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(83, 0,115607, 'OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA PETROQUIMICA', 'OSPIP', 'AVDA. SAN MARTIN 698 PA', 2200, 'SANTA FE', '', 'administracion@ospip-os.com.ar', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(84, 0,106401, 'OBRA SOCIAL DEL PERSONAL DE EDIFICIOS DE RENTA Y HORIZONTAL DE LA REPUBLICA ARGENTINA', 'OSPERYHRA', 'SARMIENTO 2026', 1044, 'CAPITAL FEDERAL', '', 'osperyh@osperyh.org.ar', 'www.fateryh.org.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(85, 0,125905, 'OBRA SOCIAL DE ARBITROS DEPORTIVOS DE LA REPUBLICA ARGENTINA', 'OSADRA', 'VIAMONTE 1835', 1056, 'CAPITAL FEDERAL', '', '', 'www.osadra.org.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(86, 0,122104, 'OBRA SOCIAL DE VIAJANTES VENDEDORES DE LA REPUBLICA ARGENTINA. (ANDAR)', 'OSVVRA', 'MORENO 2045', 1094, 'CAPITAL FEDERAL', '0800-345-26327', 'info@redsocialfuva.com.ar', 'www.redsocialfuva.org.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(87, 0,114109, 'OBRA SOCIAL DEL PERSONAL DEL PAPEL, CARTON Y QUIMICOS', 'OSPPCYQ', 'OSVALDO CRUZ 2075', 1293, 'CAPITAL FEDERAL', '0800-222-2727', 'info@ospapel.org.ar', 'www.ospapel.org.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(88, 0,121804, 'OBRA SOCIAL CONDUCTORES DE TAXIS DE CORDOBA', 'OSTC', 'SAN LUIS 373 - B. GUEMES', 5000, 'CORDOBA', '', 'osct-cba@hotmaail.com.ar', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(89, 0,102904, 'OBRA SOCIAL DEL PERSONAL DE BARRACAS DE LANAS, CUEROS Y ANEXOS', '', 'FLORENTINO AMEGHINO 1060', 1870, 'BUENOS AIRES', '0-800-222-7203', 'osblyca@uolsinectis.com.ar', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(90, 0,107107, 'OBRA SOCIAL DEL PERSONAL DEL ESPECTACULO PUBLICO', 'OSPEP', 'PASCO 148/54', 1081, 'CAPITAL FEDERAL', '', '', 'www.ospepsalud.com.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(91, 0,112004, 'OBRA SOCIAL DEL PERSONAL SUPERIOR MERCEDES BENZ ARGENTINA', 'OSPS MERCEDES', 'AVDA RIVADAVIA 10964 LINIERS', 1408, 'CAPITAL FEDERAL', '', 'obrasocial@apsmba.com.ar', 'www.apsmba.com.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(92, 0,114505, 'OBRA SOCIAL DE PATRONES DE CABOTAJE DE RIOS Y PUERTOS', '', 'GUALEGUAY 1255 / 57', 1265, 'CAPITAL FEDERAL', '', '', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(93, 0,111704, 'OBRA SOCIAL DE ENCARGADOS APUNTADORES MARITIMOS', 'OSEAM', 'MEXICO 2183 DTO A', 1222, 'CAPITAL FEDERAL', '', 'oseam@speedy.com.ar', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(94, 0,107206, 'OBRA SOCIAL DEL PERSONAL DE ESTACIONES DE SERVICIO, GARAGES, PLAYAS DE ESTACIONAMIENTO Y LAVADEROS AUTOMATICOS', 'OSPESGYPE', 'HIPOLITO YRIGOYEN 2727', 1090, 'CAPITAL FEDERAL', '', '', 'www.soesgype.org.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(95, 0,122500, 'OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA DEL VIDRIO', 'OSPIV', 'BALBASTRO 453', 1424, 'CAPITAL FEDERAL', '', '', 'www.soivavidrio.com.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(96, 0,128904, 'OBRA SOCIAL DE LOS TRABAJADORES ARGENTINOS DE CENTROS DE CONTACTOS', 'O.S.T.A.C.C,', 'ROSARIO DE SANTA FE 414', 0, 'NO IDENTIFICADA', '', '', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(97, 0,106005, 'OBRA SOCIAL DEL PERSONAL DE ENTIDADES DEPORTIVAS Y CIVILES', 'OSPEDYC', 'ALBERTI 646', 1223, 'CAPITAL FEDERAL', '', 'ospedyc@infovia.com', 'www.ospedyc.org.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(98, 0,106807, 'OBRA SOCIAL DEL PERSONAL DE LA ENSE—ANZA PRIVADA', 'OSPEP', 'AV. JUJUY 226', 1083, 'CAPITAL FEDERAL', '', 'informes@ospepweb.com.ar', 'www.ospepweb.com.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(99, 0,108100, 'OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA DEL FOSFORO, ENCENDIDO Y AFINES', 'OSPIF', 'MARCONI 652', 1870, 'BUENOS AIRES', '', 'osfosforo@hotmail.com', 'www.redospif.com.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(100, 0,117405, 'OBRA SOCIAL DEL PERSONAL DE PRENSA DE BAHIA BLANCA', '', 'LAMADRID 266', 8000, 'BUENOS AIRES', '', 'prensabblanca@bvconline.com.ar', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(101, 0,102706, 'OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA AZUCARERA', 'OSPIA', 'CONGRESO 342/8', 4000, 'TUCUMAN', '', 'ospia@tucbbs.com.ar', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(102, 0,109608, 'OBRA SOCIAL DEL PERSONAL MENSUALIZADO DEL JOCKEY CLUB DE BUENOS AIRES Y LOS HIPODROMOS DE PALERMO Y SAN ISIDRO', '', 'AVDA. CABILDO 4193', 1429, 'CAPITAL FEDERAL', '', '', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(103, 0,116006, 'OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA DEL PLASTICO', 'OSPIP', 'PAVON 4175', 1253, 'CAPITAL FEDERAL', '0800-222-6774', '', 'www.ospip.org.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(104, 0,128300, 'OBRA SOCIAL PEONES DE TAXIS DE ROSARIO', 'O.S.PE.TAX.R', 'SALTA 2882', 2000, 'SANTA FE', '', '', 'w.w.w.sptrosario.com.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(105, 0,100908, 'OBRA SOCIAL EMPLEADOS DE AGENCIAS DE INFORMES', 'OSEADI', 'LAVALLE 1783 PISO 1 - OF. A', 1048, 'CAPITAL FEDERAL', '', 'oseadi@VELOCOM.com.ar', 'WWW.OSEADI.COM.AR', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(106, 0,110602, 'OBRA SOCIAL DE LOCUTORES', 'OSDEL', 'VIDT 2011', 1425, 'CAPITAL FEDERAL', '', 'locutores@sinectis.com.ar', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(107, 0,122906, 'OBRA SOCIAL DEL PERSONAL DE ESTACIONES DE SERVICIO, GARAGES, PLAYAS Y LAVADEROS AUTOMATICOS DE LA PROVINCIA DE SANTA FE', 'OSPESGA', 'RIOBAMBA 1069', 2000, 'SANTA FE', '', 'recpcion@ospesga.com.ar', 'www.ospesga.com.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(108, 0,110701, 'OBRA SOCIAL DE LA FEDERACION ARGENTINA DE TRABAJADORES DE LUZ Y FUERZA', 'OSFATLYF', 'LIMA 163 4∞ PISO', 1073, 'CAPITAL FEDERAL', '', 'bettinottir@osfatlyf_salud.com.ar', 'www.osfatlyf-salud.com.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(109, 0,126502, 'OBRA SOCIAL DE LA CONFEDERACION DE OBREROS Y EMPLEADOS MUNICIPALES ARGENTINA ( OSCOEMA )', 'OSCOEMA', 'MORENO 970 PISO 2 OFC 15', 1091, 'CAPITAL FEDERAL', '0810-333-3057', 'oscoema@gmail.com', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(110, 0,117207, 'OBRA SOCIAL DEL PERSONAL DE PRENSA DE LA REPUBLICA ARGENTINA', 'OSPPRA', 'SOLIS 1158 PISO 3ß', 1078, 'CAPITAL FEDERAL', '', 'info@osppra.com.ar', 'www.osppra.com.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(111, 0,110909, 'OBRA SOCIAL DEL PERSONAL DE LUZ Y FUERZA DE CORDOBA', 'OSLYF', 'AVDA. GRAL PAZ 282 PISO 1', 5000, 'CORDOBA', '0800-333-3202', '', 'luzfuerzacbasalud.com.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(112, 0,120900, 'OBRA SOCIAL DEL PERSONAL DE TELEVISION', 'OSPTV', 'QUINTINO BOCAYUVA 38/50', 1181, 'CAPITAL FEDERAL', '0800-288-8872', 'info@tvsalud.com.ar', 'www.tvsalud.com.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(113, 0,127109, 'OBRA SOCIAL DEL PERSONAL DE TELECOMUNICACIONES SINDICATO BUENOS AIRES', 'OSPETELCO', '24 DE NOVIEMBRE 40', 1015, 'CAPITAL FEDERAL', '0800-999-6241', 'info@ospetelco.org', 'www.ospetelco.org', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(114, 0,100205, 'OBRA SOCIAL DE ACTORES', 'OSA', 'AYACUCHO 537', 1025, 'CAPITAL FEDERAL', '0-800-999-0301', '', 'www.osa.org.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(115, 0,107404, 'OBRA SOCIAL DEL PERSONAL DE FARMACIA', 'OSPF', 'CONSTITUCION 2066', 1254, 'CAPITAL FEDERAL', '0800-333-9820', 'privada@ospf.org.ar', 'www.ospf.org.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(116, 0,110305, 'OBRA SOCIAL DEL PERSONAL LADRILLERO', 'OSPL', 'HIPOLITO IRIGOYEN 1534 3∫ PISO', 1089, 'CAPITAL FEDERAL', '', 'autorizacionesospl@live.com.ar', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(117, 0,127307, 'OBRA SOCIAL DE TRABAJADORES VIALES Y AFINES DE LA REPUBLICA ARGENTINA', '', 'MEXICO 1399', 1097, 'CAPITAL FEDERAL', '', 'info@vialsalud.com.ar', 'www.vialsalud.com.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(118, 0,110503, 'OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA LECHERA', 'OSPIL', 'AVDA. HIPOLITO YRIGOYEN 4054', 1208, 'CAPITAL FEDERAL', '', 'obrasocial@atilra.org.ar', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(119, 0,111506, 'OBRA SOCIAL DE CAPITANES BAQUEANOS FLUVIALES DE LA MARINA MERCANTE', 'OSCAPBAQFLU', 'ARISTOBULO DEL VALLE 319', 1161, 'CAPITAL FEDERAL', '', '', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(120, 0,125509, 'OBRA SOCIAL DE LA FEDERACION ARGENTINA DEL TRABAJADOR DE LAS UNIVERSIDADES NACIONALES', 'OSFATUN', 'AV BELGRANO 3768 4TO. PISO', 1210, 'CAPITAL FEDERAL', '0-800-666--5173', 'info@osfatun.com.ar', 'www.osfatun.com.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(121, 0,101000, 'OBRA SOCIAL DEL PERSONAL DE AGUAS GASEOSAS Y AFINES', 'OSPAGA', 'BACACAY 2735/37', 1406, 'CAPITAL FEDERAL', '0800-222-677242', 'ospaga@yahoo.com.ar', 'www.ospaga.com.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(122, 0,127208, 'OBRA SOCIAL DE MANDOS MEDIOS DE TELECOMUNICACIONES EN LA REPUBLICA ARGENTINA Y MERCOSUR', 'OSMMEDT', 'URIARTE 1317', 1414, 'CAPITAL FEDERAL', '0810 777 6767', 'info@osmmedt.com.ar', 'www.osmmedt.org.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(123, 0,108407, 'OBRA SOCIAL DEL PERSONAL DE LA ACTIVIDAD FRUTICOLA', 'OSPAF', 'SAAVEDRA 121', 3200, 'ENTRE RIOS', '', 'OSPAF@YAHOO.COM.AR', 'EN CRISIS CONFORME DECRETO 1400/01 (VER OBSERV)', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(124, 0,111605, 'OBRA SOCIAL DE EMPLEADOS DE LA MARINA MERCANTE', 'OSEMM', 'BARTOLOME MITRE 3776', 1201, 'CAPITAL FEDERAL', '', '', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(125, 0,127505, 'OBRA SOCIAL DE LAS ASOCIACIONES DE EMPLEADOS DE FARMACIA', 'OSADEF', 'RINCON 1035', 1227, 'CAPITAL FEDERAL', '0800-666-2333', '', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(126, 0,112301, 'OBRA SOCIAL DEL PERSONAL DE MICROS Y OMNIBUS DE MENDOZA', 'OSPEMOM', 'CATAMARCA 382', 5500, 'MENDOZA', '', 'ospemom@ospemom.org.ar', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(127, 0,100106, 'OBRA SOCIAL PARA EL PERSONAL DE LA INDUSTRIA ACEITERA, DESMOTADORA Y AFINES', 'OSIAD', 'AVDA. BELGRANO 1370 PISO 2', 1093, 'CAPITAL FEDERAL', '0810-345-6742', 'info@osiadsalud.org.ar', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(128, 0,101109, 'OBRA SOCIAL DE ALFAJOREROS, REPOSTEROS, PIZZEROS Y HELADEROS', 'OSARPYH', 'AV. LURO 3523', 7600, 'BUENOS AIRES', '', 'osarpyh@starphymdp.com.ar', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(129, 0,103808, 'OBRA SOCIAL DEL PERSONAL DEL CAUCHO', 'OSPECA', 'VALLE 1281', 1406, 'CAPITAL FEDERAL', '', 'ospeca@fibertel.com.ar', 'www.ospeca.org.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(130, 0,119500, 'OBRA SOCIAL DEL PERSONAL DE LA SANIDAD ARGENTINA', 'OSPSA', 'DEAN FUNES 1242', 1244, 'CAPITAL FEDERAL', '', 'informes@sanidad.org.ar', 'www.sanidad.org.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(131, 0,122609, 'OBRA SOCIAL DEL PERSONAL DE LA ACTIVIDAD VITIVINICOLA', 'OSPAV', 'WARNES 1894', 1416, 'CAPITAL FEDERAL', '0800-444-6772', 'info@ospav.com.ar', 'www.ospav.com.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(132, 0,118507, 'OBRA SOCIAL DE AGENTES DE PROPAGANDA MEDICA DE ROSARIO', '', 'LAPRIDA 1063', 2000, 'SANTA FE', '0800-333-0276', 'apmsalud@osapmr.com.ar', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(133, 0,105309, 'OBRA SOCIAL DEL PERSONAL ADMINISTRATIVO Y TECNICO DE LA CONSTRUCCION Y AFINES', 'OSPATCA', 'PTE. LUIS SAENZ PE—A 1142/44', 1110, 'CAPITAL FEDERAL', '0800-333-3480', 'info@ospatca.com.ar', 'www.ospatca.com.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(134, 0,123107, 'OBRA SOCIAL TALLERISTAS A DOMICILIO', 'OSTAD', 'ACEVEDO 553', 1414, 'CAPITAL FEDERAL', '', 'ostad@fibertel.com.ar', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(135, 0,122401, 'OBRA SOCIAL DE EMPLEADOS DE LA INDUSTRIA DEL VIDRIO', 'OSEIV', 'CARABOBO 217', 1406, 'CAPITAL FEDERAL', '', 'oseiv.vidrio@hotmail.com', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(136, 0,112707, 'OBRA SOCIAL DEL PERSONAL MOSAISTA', 'OSPM', 'QUIRNO 89', 1406, 'CAPITAL FEDERAL', '', 'mosaistas@hotmail.com', 'RESOLUCION 147/12 (VER OBSERVACIONES)', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(137, 0,118002, 'OBRA SOCIAL DE EMPLEADOS DE PRENSA DE CORDOBA', 'OSEPC', 'OBISPO TREJO 365', 5000, 'CORDOBA', '', 'osepc@onenet.com.ar', 'www.prensalud.com.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(138, 0,109400, 'OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA DEL HIELO Y MERCADOS PARTICULARES', 'OSPIHMP', 'COLOMBRES 1573 (SINDICATO)', 1238, 'CAPITAL FEDERAL', '0800-666-7744', 'auditoria@ospihmp.org.ar', 'www.stihmpra.hypermart.net', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(139, 0,113700, 'OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA NAVAL', 'OSPIN', 'CHACABUCO 528', 1648, 'BUENOS AIRES', '', 'osnavales@yahoo.com.ar', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(140, 0,126809, 'OBRA SOCIAL DE CONDUCTORES DE REMISES Y AUTOS AL INSTANTE Y AFINES', 'OSCRAIA', 'CERRITO 228 - 1∫ "B"', 1010, 'CAPITAL FEDERAL', '', 'oscraia@live.com.ar', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(141, 0,126106, 'OBRA SOCIAL PARA LOS TRABAJADORES DE LA EDUCACION PRIVADA', 'OSTEP', 'SALTA 534', 1074, 'CAPITAL FEDERAL', '', 'ostep@infovia.com.ar', 'www.ostepdigital.com', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(142, 0,118903, 'OBRA SOCIAL DEL PERSONAL DE RECOLECCION Y BARRIDO DE ROSARIO', '', 'BUENOS AIRES 1635', 2000, 'SANTA FE', '', 'osprbyl@arnet.com.ar', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(143, 0,110206, 'OBRA SOCIAL DEL PERSONAL DEL JOCKEY CLUB DE ROSARIO', '', 'OVIDIO LAGOS 1571', 2000, 'SANTA FE', '', '', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(144, 0,113908, 'OBRA SOCIAL DEL PERSONAL DE PANADERIAS', 'OSPEP', 'BOEDO 168', 1206, 'CAPITAL FEDERAL', '0800-999-3861', 'info@ospep.org.ar', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(145, 0,120702, 'OBRA SOCIAL DEL PERSONAL DE LAS TELECOMUNICACIONES DE LA REPUBLICA ARGENTINA', 'OSTEL', 'AVDA JUAN DE GARAY 2569', 1256, 'CAPITAL FEDERAL', '0800-333-6783', 'compras@ostel.org', 'www.ostel.org', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(146, 0,126205, 'OBRA SOCIAL DE LOS EMPLEADOS DE COMERCIO Y ACTIVIDADES CIVILES', 'OSECAC', 'MORENO 648/50', 1091, 'CAPITAL FEDERAL', '0800-666-0400', '', 'www.osecac.org.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(147, 0,123602, 'OBRA SOCIAL DE TRABAJADORES DE PERKINS ARGENTINA S.A.I.C', 'OSTP', 'ROQUE SAENZ PE—A 1377', 5000, 'CORDOBA', '0800-444-0663', 'obrasocialperkins@hotmail.com', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(148, 0,100601, 'OBRA SOCIAL DEL PERSONAL DE AERONAVEGACION DE ENTES PRIVADOS', 'OSPADEP', 'VENEZUELA 900', 1095, 'CAPITAL FEDERAL', '0800-222-2722', 'info@ospadep.com', 'www.ospadep.com.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(149, 0,114307, 'OBRA SOCIAL TRABAJADORES PASTELEROS, CONFITEROS, PIZZEROS , HELADEROS Y ALFAJOREROS DE LA REPUBLICA ARGENTINA', 'OSTPCHPYARA', 'BOGADO 4541', 1183, 'CAPITAL FEDERAL', '', 'fatpchpya@infovia.com.ar', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(150, 0,123305, 'OBRA SOCIAL DEL PERSONAL DE SOCIEDADES DE AUTORES Y AFINES', 'OSPESA', 'MONTEVIDEO 453 (DOMICILIO PROVISORIO)', 1019, 'CAPITAL FEDERAL', '', 'ospesa@infovia.com.ar', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(151, 0,128409, 'OBRA SOCIAL DEL SINDICATO OBREROS Y EMPLEADOS DE EMPRESAS DE LIMPIEZA,SERVICIOS Y AFINES DE CORDOBA', 'OSSOELSAC', 'ENTRE RIOS 372', 5000, 'CORDOBA', '', '', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(152, 0,105408, 'OBRA SOCIAL DEL PERSONAL DE LA CONSTRUCCION', 'OSPECON', 'AVDA. BELGRANO 1862/70', 1094, 'CAPITAL FEDERAL', '0800-222-0123', 'salud@uocra.org', 'www.construirsalud.com.ar.', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(153, 0,111308, 'OBRA SOCIAL DE MAQUINISTAS DE TEATRO Y TELEVISION', '', 'AVDA CORRIENTES 1642 PISO 1 OFICINA 21', 1042, 'CAPITAL FEDERAL', '', 'osmtt@osmtt.org.ar', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(154, 0,114901, 'OBRA SOCIAL DE OFICIALES PELUQUEROS Y PEINADORES DE ROSARIO', 'OSOFPP DE ROSARIO', 'MONTEVIDEO 1488', 2000, 'SANTA FE', '', 'spprosario@sinetis.com.ar', 'www.sindicatopeluq-ros.com.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(155, 0,117702, 'OBRA SOCIAL DEL PERSONAL DE PRENSA DE MAR DEL PLATA', 'OSPREN', 'DORREGO 1734', 7600, 'BUENOS AIRES', '', 'ospren@ospren.org.ar', 'www.prensamardelplata.org.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(156, 0,127802, 'OBRA SOCIAL DE LUZ Y FUERZA DE LA PATAGONIA', 'OSLYF PATAGONIA', 'BALDOMERO CARRASCO N∫ 60', 9100, 'CHUBUT', '0800-666-4363', 'info@generarsalud.com.ar', 'www.generarsalud.com.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(157, 0,111407, 'OBRA SOCIAL DE CAPITANES DE ULTRAMAR Y OFICIALES DE LA MARINA MERCANTE', 'OSCOMM', 'AVENIDA INDEPEDENCIA 611', 1099, 'CAPITAL FEDERAL', '0800-6667266', 'secretaria@capitanes.org.ar', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(158, 0,119203, 'OBRA SOCIAL DE RELOJEROS Y JOYEROS', 'OSRJA', 'VALENTIN GOMEZ 3828', 1191, 'CAPITAL FEDERAL', '0800-333-3420', 'info@osrja.org.ar', 'www.osrja..org.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(159, 0,122005, 'OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA DEL VESTIDO', 'OSPIV', 'AVDA. RIVADAVIA 1378 PB', 1049, 'CAPITAL FEDERAL', '8009991941', 'presidencia@osvestido.com.ar', 'www.osvestido.com.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(160, 0,107909, 'OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA FIDEERA', 'OSPIF', 'RIO DE JANEIRO 55', 1405, 'CAPITAL FEDERAL', '', 'ospif-central@speedy.com.ar', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(161, 0,110008, 'OBRA SOCIAL DEL PERSONAL DE JABONEROS', 'OSPEJ', 'SARMIENTO 1113 PISO 8 B', 1041, 'CAPITAL FEDERAL', '4-383-2983', 'ospej11000-8@ciudad.com.ar', 'www.osjaboneros.com.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(162, 0,121309, 'OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA DEL TRACTOR', 'OSPIT', 'SAN LORENZO 2181', 2000, 'SANTA FE', '', 'soeita@yahoo.com.ar', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(163, 0,121903, 'OBRA SOCIAL DE VAREADORES', '', 'ENTRE RIOS 1395', 1640, 'BUENOS AIRES', '', '', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(164, 0,108001, 'OBRA SOCIAL PARA EL PERSONAL DE LA INDUSTRIA FORESTAL DE SANTIAGO DEL ESTERO', 'OSPIFSE', 'MISIONES 332', 4200, 'SANTIAGO DEL ESTERO', '', 'ingresos@ospifse.com.ar', 'www.ospifse.com.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(165, 0,112509, 'OBRA SOCIAL MODELOS ARGENTINOS', 'OSMA', 'AVDA CORRIENTES 1622 PISO 1 DTO A', 1042, 'CAPITAL FEDERAL', '', 'osmodelos@fibertel.com.ar', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(166, 0,109301, 'OBRA SOCIAL DEL PERSONAL DE CONSIGNATARIOS DEL MERCADO NACIONAL DE HACIENDA DE LINIERS', 'OSPEMER', 'LISANDRO DE LA TORRE 2337/9', 1440, 'CAPITAL FEDERAL', '', '', 'en CRISIS desde el 14/08/14 - Resol. 1291/14-SSS', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(167, 0,123701, 'OBRA SOCIAL DE PEONES DE TAXIS DE LA CAPITAL FEDERAL', 'OSPETAX', 'AVDA LA PLATA 1554/60/62/64', 1250, 'CAPITAL FEDERAL', '', 'sindicato taxis@speedy.com.ar', 'www.ospetax.org.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(168, 0,100809, 'OBRA SOCIAL DE AERONAVEGANTES', 'OSA', 'BARTOLOME MITRE 1902 - PB', 1039, 'CAPITAL FEDERAL', '0800 9999 672', 'osa@aeronavegantes.com', 'www.osa-aeronavegantes.com', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(169, 0,105705, 'OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA DEL CHACINADO Y AFINES', 'OSPICHA', 'AVDA. SAN JUAN 4229 PLANTA BAJA', 1233, 'CAPITAL FEDERAL', '', '', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(170, 0,104108, 'OBRA SOCIAL DE CERAMISTAS', 'OSCE', 'DOBLAS 629', 1424, 'CAPITAL FEDERAL', '', '', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(171, 0,108209, 'OBRA SOCIAL DE FOTOGRAFOS', 'OSFOT', 'PRINGLES 1090/92', 1183, 'CAPITAL FEDERAL', '', 'osfot@speedy.com.ar', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(172, 0,119609, 'OBRA SOCIAL DEL PERSONAL DE INSTALACIONES SANITARIAS', 'OSPIS', 'PASCO N∫ 1040', 1219, 'CAPITAL FEDERAL', '0800-555-8774', '', 'www.ospis.com.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(173, 0,102300, 'OBRA SOCIAL DEL PERSONAL DEL AZUCAR DEL INGENIO SAN MARTIN', 'OSPA', 'ISLAS MALVINAS S/N - BARRIO PATRON COSTAS', 4533, 'SALTA', '', 'ospasalta102300@gmail.com', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(174, 0,110107, 'OBRA SOCIAL DE JARDINEROS, PARQUISTAS, VIVERISTAS Y FLORICULTORES DE LA REPUBLICA ARGENTINA', 'OSJPVYF', 'LUIS SAENZ PE—A 480', 1110, 'CAPITAL FEDERAL', '0800-666-7386', 'osjard@grupoa.com.ar', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(175, 0,111902, 'OBRA SOCIAL DEL SINDICATO DE MECANICOS Y AFINES DEL TRANSPORTE AUTOMOTOR', 'OSMATA', 'AVDA. BELGRANO 665 PISO 8', 1092, 'CAPITAL FEDERAL', '4-340-7412', '', 'www.smata.com.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(176, 0,121002, 'OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA TEXTIL', 'OSPIT', 'AVDA. LA PLATA 754', 1235, 'CAPITAL FEDERAL', '0800-333-63733', 'ospit@aotra.com.ar', 'www.ospit.org.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(177, 0,128508, 'OBRA SOCIAL DE FARMACEUTICOS Y BIOQUIMICOS', 'OSFYB', 'AGUERO 1595 PISO 13', 1425, 'CAPITAL FEDERAL', '', '', 'www.safyb.org.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(178, 0,101604, 'OBRA SOCIAL DEL PERSONAL DEL AUTOMOVIL CLUB ARGENTINO', 'OSPACA', 'ANCHORENA 639 - PISO 1', 1170, 'CAPITAL FEDERAL', '0800-999-6772', '', 'www.ospaca.com', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(179, 0,111803, 'OBRA SOCIAL DEL PERSONAL MARITIMO', 'OSPM', 'VENEZUELA 1427', 1095, 'CAPITAL FEDERAL', '', 'ospm@teletel.com.ar', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(180, 0,119708, 'OBRA SOCIAL DEL PERSONAL DE SEGURIDAD COMERCIAL, INDUSTRIAL E INVESTIGACIONES PRIVADAS', 'OSPSIP', 'TUCUMAN 3689', 1189, 'CAPITAL FEDERAL', '0800-333-6777', 'info@opsip.org.ar', 'www.ospsip.org.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(181, 0,127604, 'OBRA SOCIAL PARA EL PERSONAL DE OBRAS Y SERVICIOS SANITARIOS', 'OSOSS', 'AVELLANEDA 212 PISO 3', 1405, 'CAPITAL FEDERAL', '0800-999-1702', 'presidencia@ososs.com.ar', 'www.ososs.com.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(182, 0,112400, 'OBRA SOCIAL DE LA ACTIVIDAD MINERA', 'O.S.A.M.', 'ROSARIO 434/36', 1424, 'CAPITAL FEDERAL', '', '', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(183, 0,120801, 'OBRA SOCIAL DE TRABAJADORES DE LAS COMUNICACIONES', 'OSTRAC', 'CHACABUCO 140', 1069, 'CAPITAL FEDERAL', '', 'ostrac@infovia.com.ar', 'www.aatrac.org.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(184, 0,100403, 'OBRA SOCIAL DEL PERSONAL SUPERIOR Y PROFESIONAL DE EMPRESAS AEROCOMERCIALES', 'OSPEA', 'INDEPENDENCIA 1111 - PISO 2', 1099, 'CAPITAL FEDERAL', '0800-999-8907', 'ospea@upsa-ospea.com.ar', 'www.upsa-ospea.com.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(185, 0,106104, 'OBRA SOCIAL DE EMPLEADOS DE DESPACHANTES DE ADUANA', 'OSEDA', 'CALLAO 220 PISO 6', 1022, 'CAPITAL FEDERAL', '', '', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(186, 0,115706, 'OBRA SOCIAL PARA PILOTOS DE LINEAS AEREAS COMERCIALES Y REGULARES', 'OSPLA', 'LEZICA 4047', 1202, 'CAPITAL FEDERAL', '', 'ospla@ospla.org.ar', 'www.ospla.org.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(187, 0,115102, 'OBRA SOCIAL DE TRABAJADORES DE PRENSA DE BUENOS AIRES', 'OSTPBA', 'PTE J.D. PERON 1173', 1038, 'CAPITAL FEDERAL', '0800-345-6787', 'raulbarr22@hotmail.com', 'www.ostpba.org.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(188, 0,115201, 'OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA DEL PESCADO DE MAR DEL PLATA', 'OSPIP', '12 DE OCTUBRE 4445', 7600, 'BUENOS AIRES', '', '', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(189, 0,120603, 'OBRA SOCIAL DE EMPLEADOS DEL TABACO DE LA REPUBLICA ARGENTINA', 'OSETRA', 'BOLIVIA 384', 1406, 'CAPITAL FEDERAL', '', 'osetra@advancedsl.com.ar', 'www.suetra-tabacos.com.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(190, 0,107800, 'OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA DEL FIBROCEMENTO', 'OSPIF', 'CONSTITUCION 3674', 1754, 'BUENOS AIRES', '', 'osdelfibro@hotmail.com', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(191, 0,115003, 'OBRA SOCIAL DEL PERSONAL DE LA ACTIVIDAD PERFUMISTA', 'OSPAP', 'TREINTA Y TRES ORIENTALES 148', 1182, 'CAPITAL FEDERAL', '0800-345-0332', 'ospap@hotmail.com', 'www.ospap.org.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(192, 0,116105, 'OBRA SOCIAL DE CAPATACES ESTIBADORES PORTUARIOS', 'OSCEP', 'PINZON 1012/1016', 1161, 'CAPITAL FEDERAL', '', 'capatacesport@hotmail.com', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(193, 0,118606, 'OBRA SOCIAL DEL PERSONAL DE LA PUBLICIDAD', 'OSPP', 'AVDA CORDOBA 1576', 1055, 'CAPITAL FEDERAL', '', 'ospp@ciudad.com.ar', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(194, 0,100502, 'OBRA SOCIAL DEL PERSONAL AERONAUTICO', 'OSPA', 'ANCHORENA 1266', 1425, 'CAPITAL FEDERAL', '', 'ybalbis@ospa.com.ar', 'www.ospa.com.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(195, 0,108506, 'OBRA SOCIAL DEL PERSONAL DE MANIPULEO, EMPAQUE Y EXPEDICION DE FRUTA FRESCA Y HORTALIZAS DE CUYO', 'OSFYHC', 'MONTECASEROS 1147', 5500, 'MENDOZA', '', '', 'EN CRISIS CONFORME DECRETO 1400/01 - (VER OBSERVAC', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(196, 0,115300, 'OBRA SOCIAL DE PETROLEROS', 'OSPE', 'AVDA. L. ALEM 692 1∫ PISO', 1001, 'CAPITAL FEDERAL', '0800-444-6773', 'informes@ospesalud.com.ar', 'www.ospesalud.com.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(197, 0,125707, 'OBRA SOCIAL UNION PERSONAL DE LA UNION DEL PERSONAL CIVIL DE LA NACION', 'OSPCN', 'TUCUMAN 949', 1049, 'CAPITAL FEDERAL', '0810-8888646', 'info@unionpersonal.com.ar', 'www.unionpersonal.com.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(198, 0,127703, 'OBRA SOCIAL PERSONAL ESTACIONES DE SERVICIO,GARAGES,PLAYAS Y LAVADEROS DE LA PROVINCIA DEL CHACO', 'OSPESCHA', 'JULIO A. ROCA 755', 3500, 'CHACO', '', 'soesgypechaco@gigared.com', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(199, 0,106609, 'OBRA SOCIAL ELECTRICISTAS NAVALES', 'OSEN', 'AVDA JUAN DE GARAY 1900', 1256, 'CAPITAL FEDERAL', '', 'info@osensalud.com.ar', 'www.osensalud.com.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(200, 0,115508, 'OBRA SOCIAL DE PETROLEROS DE CORDOBA', 'O.S.PE.COR', 'AYACUCHO 575 -BARRIO. GRAL. GUEMES', 5000, 'CORDOBA', '4244014', 'afiliados@ospecor.com.ar', 'www.ospecor.com.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(201, 0,125301, 'OBRA SOCIAL FEDERAL DE LA FEDERACION NACIONAL DE TRABAJADORES DE OBRAS SANITARIAS', 'OSFFENTOS', 'PASCO 580 - PB', 1219, 'CAPITAL FEDERAL', '0800-555-1133', 'osffentos@fentos.org. ar.', 'www.fentos.org.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(202, 0,106302, 'OBRA SOCIAL DE DOCENTES PARTICULARES', 'OSDOP', 'BARTOLOME MITRE 2233', 1039, 'CAPITAL FEDERAL', '0800-6666-450', '', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(203, 0,106906, 'OBRA SOCIAL DEL PERSONAL DE ESCRIBANIAS DE LA PROVINCIA DE BUENOS AIRES', 'OSPEPBA', 'CALLE 45 N∫ 509', 1900, 'BUENOS AIRES', '', 'social@personalescribanias.org', 'www.personalescribanias.org.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(204, 0,126304, 'OBRA SOCIAL SERVICIOS SOCIALES BANCARIOS', 'OSBA', '25 DE MAYO 182', 1002, 'CAPITAL FEDERAL', '0800-555-6722', 'info@osba.com.ar', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(205, 0,115409, 'OBRA SOCIAL DEL PETROLEO Y GAS PRIVADO', 'OSPEGAP', 'AV. CASEROS 715', 1152, 'CAPITAL FEDERAL', '0800-555-6773', 'ospegap@petroleoygas.com.ar', 'www.petroleoygas.com.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(206, 0,119906, 'OBRA SOCIAL DE SERENOS DE BUQUES', '', 'BERNARDO DE IRIGOYEN 972/4 PISO 9 OF. 45', 1072, 'CAPITAL FEDERAL', '0800-345-7332', 'ossdeb@fideisalud.com.ar', 'www.fideisalud.com.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(207, 0,123503, 'OBRA SOCIAL DEL PERSONAL DE PRENSA DE TUCUMAN', 'OSPRENTUC', 'JUNIN 775', 4000, 'TUCUMAN', '', 'osprentuc@yahoo.com', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(208, 0,115805, 'OBRA SOCIAL DEL PERSONAL DE FABRICAS DE PINTURA', 'UPFPARA', 'NAZCA 845', 1406, 'CAPITAL FEDERAL', '0800-999-8525', 'osocial@ospfp.org.ar', 'http://www.ospfp.org.ar/', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(209, 0,105804, 'OBRA SOCIAL DE CHOFERES DE CAMIONES', 'OSCHOCA', 'SAN JOSE 1775/81', 1136, 'CAPITAL FEDERAL', '0800-777-0020', 'info@camioneros-ba.org.ar', 'www.camioneros-ba.org.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(210, 0,128805, 'OBRA SOCIAL DEL PERSONAL ADUANERO DE LA REPUBLICA ARGENTINA', 'OSPAD', 'PERU 625', 1068, 'CAPITAL FEDERAL', '', 'info.ospad@gmail.com', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(211, 0,126007, 'OBRA SOCIAL DE LA FEDERACION GREMIAL DEL PERSONAL DE LA INDUSTRIA DE LA CARNE Y SUS DERIVADOS', '', 'HIPOLITO YRIGOYEN 746', 1086, 'CAPITAL FEDERAL', '0800-222-7938', '', 'www.obrasocialdelacarne.org.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(212, 0,109004, 'OBRA SOCIAL DEL PERSONAL GRAFICO', 'OSPG', 'AVDA. BELGRANO 2530', 1096, 'CAPITAL FEDERAL', '', '', '', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(213, 0,101208, 'OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA DE LA ALIMENTACION', 'OSPIA', 'VENEZUELA 1326', 1096, 'CAPITAL FEDERAL', '0800-666-6774', 'ospiacentral@ospia.org.ar', 'www.ospia.org.ar', '');
INSERT INTO obra_social (id, version, rnos, denominacion, sigla, domicilio, codigo_postal, provincia, telefono, otros_telefonos, e_mail, web) VALUES(214, 0,103709, 'OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA DEL CAUCHO', 'OSPIC', 'CONGRESO 2033', 1428, 'CAPITAL FEDERAL', '', 'info@ospic-caucho.org.ar', 'www.ospic-caucho.org.ar', '');


-- Medicos


INSERT INTO medico (id, version, nombre, apellido, fecha_nacimiento, nro_matricula, id_especialidad) VALUES
(1, 0, 'HORACIO IRENEO FRANCISCO', 'BOSIO', '1970-01-01', 1, 1);



